[WIP] Add free and paid online-extensions.js files for custom quota messages
openshift/online-console-extensions pull request #40
Opened 2018-07-12 17:47 UTC by damemi

Card: https://trello.com/c/BkleYWax/958-2-pro-provide-custom-messages-for-hitting-quotas

2018-07-12 17:58 UTC, dak1n1 commented
I always like to run wording by @wgordon17 . The current wording is: `Upgrade to OpenShift Online Pro if you need more resources.` ... I'd probably try to find a way to remove "you" from the sentence and say "Add additional memory by upgrading to Pro". Or something... I'm not the best at words. Just my opinion.

Thanks for CCing me on this change. It can probably go out with next week's update.

2018-07-12 19:11 UTC, wgordon17 requested changes
Wow, it's a lot harder to remove the "you" from the Pro plan messaging than I would've thought. I put one suggestion in there without "you", but it sounds kinda weird. I'll let @damemi pick which he likes.

I would also like to see `persistentvolumeclaims` and `requests.storage` added as notification messages.

2018-07-12 19:11 UTC, wgordon17 commented on free/ui/assets/extensions/free-online-extensions.js
> +    "limits.cpu": "Upgrade to <a href=\""+window.OPENSHIFT_EXTENSION_PROPERTIES.account_url+"/register/plan\">OpenShift Online Pro</a> if you need more resources"
Some suggested edits:

Get access to additional resources by upgrading to <a>OpenShift Online Pro</a>.
Access additional resources by upgrade to <a>OpenShift Online Pro</a>.
Upgrade to <a>OpenShift Online Pro</a> for access to additional resources.
<a>OpenShift Online Pro</a> provides additional resources.

2018-07-12 19:11 UTC, wgordon17 commented on paid/ui/assets/extensions/paid-online-extensions.js
> +    "limits.cpu": "You can <a href=\""+window.OPENSHIFT_EXTENSION_PROPERTIES.account_url+"\">upgrade your plan</a> if you need more resources"
Some suggested edits:

- `<a>Add additional resources</a> to increase the quota.`
- `<a>Manage your subscription</a> to add additional resources.`
- `<a>Manage your subscription</a> to increase the quota.`

2018-07-16 17:49 UTC, damemi commented
@sspeiche does this wording/approach look good to you?

2018-07-16 18:48 UTC, wgordon17 approved these changes

2018-07-17 20:49 UTC, abhgupta commented
/lgtm

2018-07-17 20:51 UTC, merged